### PR TITLE
Add backgroundColor and labelColor for Donut

### PR DESCRIPTION
**Pull request by sgotre**
I would need these both here. They were not documented at morris.js (PR for doc update  here: https://github.com/morrisjs/morris.js/pull/654)  

Take care, i have not tested this

### CODE REVIEW

**Comment by stewones** [comment]
hi @sgotre 
thanks for contributing but we need tests for new features.  I'll review and patch asap

**Comment by skol-pro** [comment]
I was about to pull request this too. I confirm it's working.

**Comment by stewones** [comment]
@sgotre
i'm able to accept but this PR does not inlude a minified version
you should run gulp build before commit. like mentioned in [contributing](https://github.com/stewones/angular-morris-chart/blob/master/CONTRIBUTING.md)

**Comment by sgotre** [comment]
I will close this PR for a new and tested one.

**Pull request closed without merging**
